// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Navbar from "@/components/PageComponents/Navbar";
import ClientShell from "@/components/Layout/ClientShell";
import { ProductsProvider } from "@/app/context/productContext";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ProductsProvider>
          <nav className="hidden md:flex justify-center h-10">
            <Navbar />
          </nav>

          <ClientShell>{children}</ClientShell>
        </ProductsProvider>
        {/* Footer and sidebar are handled by ClientShell (client-side) */}
      </body>
      
    </html>
  );
}