// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/ui/app-sidebar";
import Navbar from "@/components/PageComponents/Navbar";
import { ProductsProvider } from "@/app/context/productContext";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
   const categories = [
    {
      name: 'Shirt',
      description: 'Formal and casual shirts for every occasion',
      items: '200+ products'
    },
    {
      name: 'T-Shirt',
      description: 'Comfortable cotton t-shirts in various styles',
      items: '350+ products'
    },
    {
      name: 'Pant',
      description: 'Jeans, formal pants, and casual trousers',
      items: '180+ products'
    },
    {
      name: 'TrackPants',
      description: 'Comfortable athletic and casual track pants',
      items: '120+ products'
    },
    {
      name: 'Hoddies',
      description: 'Warm and stylish hoodies for cool days',
      items: '90+ products'
    },
    {
      name: 'OverSize T-Shirt',
      description: 'Trendy oversized t-shirts for street style',
      items: '75+ products'
    }
  ];
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ProductsProvider>
          <div className="flex flex-col min-h-screen relative">
            {/* Navbar (only on md+) */}
            <nav className="hidden md:flex justify-center h-10">
              <Navbar />
            </nav>

            <SidebarProvider>
              {/* Sidebar + Trigger wrapper */}
              <div className="absolute top-4 md:top-6 left-0 h-full z-50 flex item-center">
                <AppSidebar />
                <SidebarTrigger />
              </div>

              {/* Main content (behind sidebar) */}
              <main className="flex-1 w-full relative z-0 mt-10 md:mt-0">
                {children}
              </main>
            </SidebarProvider>
          </div>
        </ProductsProvider>
        <footer className="bg-gray-900 text-white py-12">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
            <div>
              <h3 className="text-xl font-bold mb-4">Brand</h3>
              <p className="text-gray-400">
                Your one-stop destination for trendy and comfortable clothing.
              </p>
            </div>
            <div>
              <h4 className="font-semibold mb-4">Categories</h4>
              <ul className="space-y-2 text-gray-400">
                {categories.map((category, index) => (
                  <li key={index}>
                    <a href="#" className="hover:text-white transition duration-300">
                      {category.name}
                    </a>
                  </li>
                ))}
              </ul>
            </div>
            <div>
              <h4 className="font-semibold mb-4">Customer Service</h4>
              <ul className="space-y-2 text-gray-400">
                <li><a href="#" className="hover:text-white transition duration-300">Contact Us</a></li>
                <li><a href="#" className="hover:text-white transition duration-300">Shipping Info</a></li>
                <li><a href="#" className="hover:text-white transition duration-300">Returns</a></li>
                <li><a href="#" className="hover:text-white transition duration-300">Size Guide</a></li>
              </ul>
            </div>
            <div>
              <h4 className="font-semibold mb-4">Newsletter</h4>
              <p className="text-gray-400 mb-4">Subscribe for updates and offers</p>
              <div className="flex">
                <input
                  type="email"
                  placeholder="Enter your email"
                  className="px-4 py-2 rounded-l-lg text-gray-900 flex-1"
                />
                <button className="bg-blue-600 px-4 py-2 rounded-r-lg hover:bg-blue-700 transition duration-300">
                  Subscribe
                </button>
              </div>
            </div>
          </div>
          <div className="border-t border-gray-800 mt-8 pt-8 text-center text-gray-400">
            <p>&copy; 2024 FashionStore. All rights reserved.</p>
          </div>
        </div>
      </footer>
      </body>
      
    </html>
  );
}